import subprocess


def main():
    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """

    body = """
    inputType = input("Enter 'txt_file' to read from file or press Enter to input values manually: ")

    if inputType == 'txt_file':
        f = open('q1.txt', 'r')
        S = f.readline().strip().split(',')
        n = int(f.readline().strip())
        V = f.readline().strip().split(',')
        F = f.readline().strip().split(',')
        sigma = f.readline().strip().split(',')
        G = f.readline().strip()
        f.close()

    else:
        print("Enter values for S, n, V, F, sigma, and G")
        S = input("Enter S (comma-separated): ").strip().split(',')
        n = int(input("Enter n (number of group-by attributes): "))
        V = input("Enter V (comma-separated group-by attributes): ").strip().split(',')
        F = input("Enter F (comma-separated aggregates like sum_x,avg_y): ").strip().split(',')
        sigma = input("Enter sigma conditions (e.g. 1.state=NJ,2.city=NY): ").strip().split(',')
        G = input("Enter having clause (or leave blank): ").strip()

    #finished input parsing, need next steps
    mf_struct = {}
    
    """

    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    {body}
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code
    subprocess.run(["python", "_generated.py"])


if "__main__" == __name__:
    main()
